###
PATCH http://localhost:5000/users/65d2f6817ee05d0485cd2498
Content-Type: application/json

{
    "password": "11111"
}

###
GET http://localhost:5000/users/65dd84d774d3e453a071fb9a

###
POST http://localhost:5000/users/login
Content-Type: application/json

{
    "email": "email@gmail.com",
    "password" : "12345"
}